### ISSUE TITLE
UglifyJS falls down because of this lib

### ISSUE THREAD

**Issue by krvital** [Ohar/forEachTimeout#1]
UglifyJS doesn't know anything about ES6, so it falls down when meet with `foreach-timeout.js` file.
Please consider distribution ES5 version of this library.

![2018-05-09_00-39-17](https://user-images.githubusercontent.com/811386/39776037-799524d2-5321-11e8-9014-ad249bffd5fd.png)

**Comment by Ohar** [comment]
I suppose it is not `foreach-timeout`'s problem, bcz, as [said one of UglifyJS team member](https://github.com/mishoo/UglifyJS2/issues/968#issuecomment-183048856): 

> The release version of uglify-js only supports ES5. You could always run your code through babel and import it into the release version of uglify.
